---

- name: ensure category exists
  vmware_category:
    hostname: "{{ lookup('env', 'VMWARE_HOST')|default(providers.vcenter.hostname) }}"
    username: "{{ lookup('env', 'VMWARE_USER')|default(providers.vcenter.username) }}"
    password: "{{ lookup('env', 'VMWARE_PASSWORD')|default(providers.vcenter.password) }}"
    validate_certs: no
    category_name: "{{ item }}"
    category_description: ""
    category_cardinality: 'multiple'
    state: present
  register: vcenter_category_info
  loop:
    - app_name
    - role

- name: create tags
  vmware_tag:
    hostname: "{{ lookup('env', 'VMWARE_HOST')|default(providers.vcenter.hostname) }}"
    username: "{{ lookup('env', 'VMWARE_USER')|default(providers.vcenter.username) }}"
    password: "{{ lookup('env', 'VMWARE_PASSWORD')|default(providers.vcenter.password) }}"
    validate_certs: no
    category_id: "{{ item.1.category_results.category_id }}"
    tag_name: "{{ item.0.item.item[item.1.item] | default('') }}"
    tag_description: ""
    state: present
  with_nested:
    - "{{ instances.results }}"
    - "{{ vcenter_category_info.results }}"
  when:
    - item.0.instance is defined
    - item.1.category_results.category_id
  ignore_errors: yes

- name: add tags
  vmware_tag_manager:
    hostname: "{{ lookup('env', 'VMWARE_HOST')|default(providers.vcenter.hostname) }}"
    username: "{{ lookup('env', 'VMWARE_USER')|default(providers.vcenter.username) }}"
    password: "{{ lookup('env', 'VMWARE_PASSWORD')|default(providers.vcenter.password) }}"
    validate_certs: no
    object_name: "{{ item.item.item.name | default(item.instance.hw_name) }}"
    object_type: VirtualMachine
    state: present
    tag_names:
      - "app_name:{{ item.item.item.app_name | default('') }}"
      - "role:{{ item.item.item.role | default('') }}"
  loop: "{{ instances.results }}"
  when:
    - item.instance is defined
  ignore_errors: yes